Repository Chandresh2702/login-page, pull requests merged in 2022-10, with the labels that each got.

#1 changing padding
  adding page/lib/main.dart
Labels: hacktoberfest, hacktoberfest-accepted

#2 allowing to see the password
  login-exchange/lib/signup.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#3 alligning title in centre
  home-page/lib/screens/home.dart
Labels: bug, hacktoberfest, hacktoberfest-accepted

#4 changing page options
  product info page/lib/productinfo.dart
Labels: bug, hacktoberfest, hacktoberfest-accepted

#5 updating readme
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#6 updating testsuit
  home-page/test/widget_test.dart
Labels: hacktoberfest, hacktoberfest-accepted

#7 Delete image10.jpg
  E-xchange/assets/images/image10.jpg
Labels: hacktoberfest, hacktoberfest-accepted
